### ISSUE TITLE
add example/demo type?

### ISSUE THREAD

**Issue by e-cloud** [adjohnson916/conventional-commit-types#3]
for a front-end project, it's common to have some (simple)demo live inside the project.
adding a related type to it would be great

**Comment by adjohnson916** [comment]
@e-cloud For now the intention is to stick with the [standard Angular types](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#type). This library can be extended via your own module, and tools like cz-cli and validate-commit-msg can be configured to use that custom module.

**Comment by e-cloud** [comment]
gotcha, that's ok
